"""Renders a VisualPlan as a fresh ASSET.md file matching
templates/ASSET.md. Every Historical authenticity classification is
explicit, never defaulted — see CONTRACT.md's Forbidden actions and the
Visual Safety Rule in classification.py.
"""
from __future__ import annotations

from .models import VisualPlan


def render_asset_markdown(plan: VisualPlan, content_id: str) -> str:
    asset_stem = plan.asset_filename[: -len(".md")]
    asset_id = f"{content_id}-{asset_stem}"
    generation_prompt = (
        "not yet drafted" if plan.generated_or_retrieved == "GENERATED" else "N/A (retrieved, not generated)"
    )

    return f"""# Asset: {plan.scene.filename} visual requirement

Generated by `agents/visual_planner` (Phase 7B MVP) per
`agents/visual_planner/CONTRACT.md`. Specifies the requirement only — no
generation or retrieval has happened.

| Field | Value |
|---|---|
| Asset ID | `{asset_id}` |
| Content ID | `{content_id}` |
| Asset type | `{plan.asset_type}` |
| Intended scene | `scenes/{plan.scene.filename}` |

## Provenance

| Field | Value |
|---|---|
| Generated vs. retrieved | `{plan.generated_or_retrieved}` |
| Source | not yet sourced |
| Source URL / reference | N/A |
| Generation prompt/reference | {generation_prompt} |

## Historical authenticity classification

| Field | Value |
|---|---|
| Classification | `{plan.authenticity.value}` |
| Basis for classification | {plan.basis} |

## Licensing / copyright

| Field | Value |
|---|---|
| Licensing/provenance status | `UNVERIFIED` |
| Copyright/provenance notes | not yet checked — nothing has been sourced or generated |

## Technical

| Field | Value |
|---|---|
| Dimensions / aspect ratio | TBD |
| File reference | not yet produced |

## Verification status

`NOT_STARTED`

Nothing to verify — asset does not exist yet.
"""
