"""Renders a ThumbnailResult as a full templates/THUMBNAIL.md file."""
from __future__ import annotations

from datetime import date, datetime, timezone

from .models import ThumbnailResult


def render_thumbnail_markdown(result: ThumbnailResult, content_id: str, today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()
    spec = result.spec

    rendered_note = (
        " Phase 8 additionally rendered a real, deliberately non-photorealistic "
        "illustration from this spec — see 'Rendered image' below."
        if result.image_bytes is not None
        else " A specification only — no image rendered for this run."
    )

    return f"""# Thumbnail: {content_id}

Generated by `agents/thumbnail` (Phase 7D MVP) per
`agents/thumbnail/CONTRACT.md`.{rendered_note}

| Field | Value |
|---|---|
| Thumbnail ID | `{result.thumbnail_id}` |
| Content ID | `{content_id}` |
| Production ID | `{result.production_id}` |
| Thumbnail content hash | `{result.thumbnail_content_hash}` |

## Concept

| Field | Value |
|---|---|
| Title concept | {spec.title_concept} |
| Visual concept | {spec.visual_concept} |
| Text overlay | {spec.text_overlay} |
| Focal subject | {spec.focal_subject} |
| Composition | {spec.composition} |

## Claim / theme relationship

{result.claim_theme_relationship}

## Authenticity considerations

{result.authenticity_considerations}

## Generation strategy

{result.generation_strategy}

## Rendered image

| Field | Value |
|---|---|
| Reference | `{result.image_reference}` |

## Thumbnail status

`{result.thumbnail_status}`

Generated on {today.isoformat()}.
"""
