"""Renders an OriginalityReviewResult as a REVIEW.md file matching
templates/REVIEW.md's structure, role ORIGINALITY_REVIEWER.
"""
from __future__ import annotations

from datetime import date, datetime, timezone

from .models import OriginalityReviewResult

REVIEWER_LABEL = "AI-assisted: originality-reviewer-agent-mvp (pending human confirmation)"
ROLE = "ORIGINALITY_REVIEWER"


def render_review_markdown(result: OriginalityReviewResult, attempt: int, today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()
    reasons = "\n".join(f"{i}. {r}" for i, r in enumerate(result.reasons, 1)) or "(none)"
    required = (
        "\n".join(f"- {c}" for c in result.required_changes)
        if result.required_changes
        else "(none — verdict is PASS)"
    )
    signal_lines = "\n".join(
        f"- {e.signal.value}: {e.risk_level.value} — {e.reason}"
        for e in result.signal_evaluations
    )
    notes = "\n".join(f"- {n}" for n in result.notes) or "(none)"

    return f"""# Review: {ROLE} attempt {attempt} — {result.content_id}

Generated by `agents/originality` (Phase 6 MVP) per
`agents/originality/CONTRACT.md`. Not a substitute for human sign-off —
see `CONSTITUTION.md` rule 1. This is not a plagiarism/legal
determination — see `agents/originality/README.md` "Core principle" and
"Known limitations" before treating any result here as a certification.

| Field | Value |
|---|---|
| Content ID | `{result.content_id}` |
| Reviewer role | `{ROLE}` |
| Reviewer | {REVIEWER_LABEL} |
| Review date | {today.isoformat()} |
| Verdict | `{result.verdict.value}` |
| Reviewed content hash | `{result.content_hash}` |

## Reasons

{reasons}

## Required changes (if REVISION_REQUIRED)

{required}

## Notes

Signal evaluations:

{signal_lines}

{notes}
"""
