"""Renders a ProductionQAResult as a full templates/PRODUCTION_QA.md
file."""
from __future__ import annotations

from datetime import date, datetime, timezone

from .models import ProductionQAResult

AREA_ORDER = ["Content", "Voice", "Assets", "Timeline", "Captions", "Thumbnail", "Output"]


def render_production_qa_markdown(result: ProductionQAResult, content_id: str, today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()

    by_area: dict[str, list] = {}
    for c in result.checks:
        by_area.setdefault(c.area, []).append(c)

    sections = []
    for area in AREA_ORDER:
        area_checks = by_area.get(area, [])
        if area_checks:
            lines = "\n".join(
                f"- {c.check} — `{'PASS' if c.passed else 'FAIL'}` — {c.note}" for c in area_checks
            )
        else:
            lines = "- (no checks ran)"
        sections.append(f"### {area}\n\n{lines}")
    checks_text = "\n\n".join(sections)

    reasons_text = "\n".join(f"- {r}" for r in result.reasons) or "(none — all checks passed)"

    return f"""# Production QA: {content_id}

Generated by `agents/production_qa` (Phase 7D MVP) per
`agents/production_qa/CONTRACT.md`. An automated, structural readiness
check — never a substitute for `templates/VIDEO_QA.md`'s human
checklist/final approval, and never itself an approval.

| Field | Value |
|---|---|
| Production QA ID | `{result.qa_id}` |
| Content ID | `{content_id}` |
| Production ID | `{result.production_id}` |
| QA date | {today.isoformat()} |
| Verdict | `{result.verdict}` |

## Checks

{checks_text}

## Reasons

{reasons_text}

## Notes

Structural readiness only — never a creative/editorial judgment, never
an approval, never a publish action. A human must still complete
`templates/VIDEO_QA.md` and its final approval before anything may
reach `READY_TO_PUBLISH`.
"""
