"""Tests 32-43: a fully valid production passes; a missing/stale asset,
stale voice, missing provenance, caption mismatch, thumbnail
misrepresentation, missing output, and hash mismatch are all detected
correctly (BLOCKED for staleness/absence, REVISION_REQUIRED for a
present-but-incomplete artifact); protected fields stay protected; the
agent can never publish or approve content.
"""
import re
import tempfile
import unittest
from pathlib import Path

from ..src import mutate
from ..src.pipeline import run_production_qa
from .builders import build_passing_item, build_qa_ready_item

GOLDEN_SAMPLE = (
    Path(__file__).resolve().parents[3]
    / "content" / "what-if" / "wi-20260902-black-death-modern-medicine"
)


class ProductionQAPipelineTests(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self._tmp.cleanup)
        self.root = Path(self._tmp.name) / "item"

    # --- Test 32: fully valid production -> PASS ---
    def test_fully_valid_production_passes(self):
        build_passing_item(self.root)
        result = run_production_qa(self.root, apply=True)
        self.assertEqual(result.verdict, "PASS")
        self.assertEqual(result.reasons, [])
        self.assertTrue(result.produced)

    def test_unapproved_content_blocks(self):
        from ...producer.tests.builders import build_minimal_item
        build_minimal_item(self.root, status="SCRIPT")
        result = run_production_qa(self.root, apply=True)
        self.assertEqual(result.verdict, "BLOCKED")
        self.assertIn("APPROVED", result.blocked_reason)

    def test_golden_sample_never_modified(self):
        if not GOLDEN_SAMPLE.is_dir():
            self.skipTest("golden sample not found")
        before = {p: p.read_text(encoding="utf-8") for p in GOLDEN_SAMPLE.rglob("*.md")}
        result = run_production_qa(GOLDEN_SAMPLE, apply=True)
        after = {p: p.read_text(encoding="utf-8") for p in GOLDEN_SAMPLE.rglob("*.md")}
        self.assertEqual(result.verdict, "BLOCKED")
        self.assertEqual(before, after)

    # --- Test 33: missing asset -> REVISION_REQUIRED/BLOCKED ---
    def test_missing_asset_causes_revision_required(self):
        build_passing_item(self.root)
        (self.root / "assets" / "asset-02.md").unlink()
        result = run_production_qa(self.root, apply=True)
        self.assertIn(result.verdict, ("REVISION_REQUIRED", "BLOCKED"))
        self.assertTrue(any("asset exists" in r for r in result.reasons) or result.blocked)

    # --- Test 34: stale voice -> BLOCKED ---
    def test_stale_voice_blocks(self):
        build_passing_item(self.root)
        voice_path = self.root / "voice" / "voice-01.md"
        text = voice_path.read_text(encoding="utf-8")
        line = [l for l in text.splitlines() if l.startswith("| Script content hash |")][0]
        voice_path.write_text(text.replace(line, "| Script content hash | `0000000000stale` |"), encoding="utf-8")

        result = run_production_qa(self.root, apply=True)
        self.assertEqual(result.verdict, "BLOCKED")
        self.assertIn("stale", result.blocked_reason.lower())
        self.assertFalse(result.produced)

    # --- Test 35: stale asset -> BLOCKED ---
    def test_stale_asset_blocks(self):
        build_passing_item(self.root)
        asset_path = self.root / "assets" / "asset-02.md"
        text = asset_path.read_text(encoding="utf-8")
        line = [l for l in text.splitlines() if l.startswith("| Scene/visual content hash |")][0]
        asset_path.write_text(text.replace(line, "| Scene/visual content hash | `0000000000stale` |"), encoding="utf-8")

        result = run_production_qa(self.root, apply=True)
        self.assertEqual(result.verdict, "BLOCKED")
        self.assertIn("stale", result.blocked_reason.lower())
        self.assertFalse(result.produced)

    # --- Test 36: missing provenance -> REVISION_REQUIRED/BLOCKED ---
    def test_missing_provenance_causes_revision_required(self):
        build_passing_item(self.root)
        asset_path = self.root / "assets" / "asset-02.md"
        text = asset_path.read_text(encoding="utf-8")
        text = text.replace(
            "| Source | generated by local-test-generated-asset-provider |",
            "| Source |  |",
        )
        asset_path.write_text(text, encoding="utf-8")

        result = run_production_qa(self.root, apply=True)
        self.assertIn(result.verdict, ("REVISION_REQUIRED", "BLOCKED"))
        self.assertTrue(any("provenance recorded" in r for r in result.reasons) or result.blocked)

    # --- Test 37: caption mismatch -> REVISION_REQUIRED ---
    def test_caption_mismatch_causes_revision_required(self):
        build_passing_item(self.root)
        captions_path = self.root / "captions" / "captions-01.md"
        text = captions_path.read_text(encoding="utf-8")
        # Corrupt one caption's text so it no longer matches the source narration.
        text = re.sub(
            r"(\| 1 \| `0\.0s` \| `[^`]+` \| ).*?( \|)",
            r"\1An entirely fabricated caption not in the narration.\2",
            text, count=1,
        )
        captions_path.write_text(text, encoding="utf-8")

        result = run_production_qa(self.root, apply=True)
        self.assertEqual(result.verdict, "REVISION_REQUIRED")
        self.assertTrue(any("map to narration" in r for r in result.reasons))

    # --- Test 38: thumbnail misrepresentation -> REVISION_REQUIRED ---
    def test_thumbnail_misrepresentation_causes_revision_required(self):
        build_passing_item(self.root)
        thumbnail_path = self.root / "thumbnail" / "thumbnail-01.md"
        text = thumbnail_path.read_text(encoding="utf-8")
        text = text.replace(
            "This production includes hypothetical/generated content "
            "(GENERATED_RECONSTRUCTION) in at least one scene's asset — the thumbnail "
            "must not present it as authentic historical media. See assets/asset-<n>.md "
            "for the exact classification per scene.",
            "It definitely happened exactly like this.",
        )
        thumbnail_path.write_text(text, encoding="utf-8")

        result = run_production_qa(self.root, apply=True)
        self.assertEqual(result.verdict, "REVISION_REQUIRED")
        self.assertTrue(any("false factual implication" in r for r in result.reasons))

    # --- Test 39: missing video artifact -> BLOCKED ---
    def test_missing_video_artifact_blocks(self):
        build_passing_item(self.root)
        (self.root / "timeline" / "timeline-01.md").unlink()
        result = run_production_qa(self.root, apply=True)
        self.assertEqual(result.verdict, "BLOCKED")
        self.assertIn("timeline", result.blocked_reason.lower())

    # --- Test 40: hash mismatch -> BLOCKED ---
    def test_production_hash_mismatch_blocks(self):
        build_passing_item(self.root)
        production_path = self.root / "PRODUCTION.md"
        text = production_path.read_text(encoding="utf-8")
        line = [l for l in text.splitlines() if l.startswith("| Script content hash |")][0]
        production_path.write_text(text.replace(line, "| Script content hash | `0000000000stale` |"), encoding="utf-8")

        result = run_production_qa(self.root, apply=True)
        self.assertEqual(result.verdict, "BLOCKED")
        self.assertIn("stale", result.blocked_reason.lower())

    # --- Test 41: protected fields cannot be modified ---
    def test_mutate_rejects_non_whitelisted_filename(self):
        with self.assertRaises(PermissionError):
            mutate.write_qa_file(self.root, "not-qa.md", "content")

    def test_mutate_rejects_blocked_or_system_error_as_production_qa_state(self):
        with self.assertRaises(PermissionError):
            mutate.apply_production_qa_state("some text", "BLOCKED", "notes", None)

    def test_apply_never_touches_claims_or_script(self):
        build_passing_item(self.root)
        claims_before = {
            p: p.read_text(encoding="utf-8") for p in (self.root / "claims").glob("*.md")
        }
        script_before = (self.root / "SCRIPT.md").read_text(encoding="utf-8")
        run_production_qa(self.root, apply=True)
        claims_after = {
            p: p.read_text(encoding="utf-8") for p in (self.root / "claims").glob("*.md")
        }
        self.assertEqual(claims_before, claims_after)
        self.assertEqual((self.root / "SCRIPT.md").read_text(encoding="utf-8"), script_before)

    def test_apply_never_touches_human_review_state(self):
        build_passing_item(self.root)
        before_text = (self.root / "PRODUCTION.md").read_text(encoding="utf-8")
        before_human_review = before_text.split("## Human review state", 1)[1]

        run_production_qa(self.root, apply=True)

        after_text = (self.root / "PRODUCTION.md").read_text(encoding="utf-8")
        after_human_review = after_text.split("## Human review state", 1)[1]
        self.assertEqual(before_human_review, after_human_review)

    # --- Test 42: QA cannot publish ---
    def test_no_publishing_capability_in_source(self):
        import ast
        src_dir = Path(__file__).resolve().parents[1] / "src"
        forbidden = {"upload", "publish", "post_video", "youtube"}
        for py_file in src_dir.glob("*.py"):
            tree = ast.parse(py_file.read_text(encoding="utf-8"), filename=str(py_file))
            for node in ast.walk(tree):
                if isinstance(node, ast.Name):
                    self.assertNotIn(node.id.lower(), forbidden, f"{py_file}: {node.id!r}")
                if isinstance(node, ast.Attribute):
                    self.assertNotIn(node.attr.lower(), forbidden, f"{py_file}: {node.attr!r}")

    def test_production_status_never_set_to_published_or_ready_to_publish(self):
        build_passing_item(self.root)
        run_production_qa(self.root, apply=True)
        production_text = (self.root / "PRODUCTION.md").read_text(encoding="utf-8")
        self.assertIn("| Production status | `HUMAN_REVIEW` |", production_text)
        self.assertNotIn("| Production status | `READY_TO_PUBLISH` |", production_text)
        self.assertNotIn("| Production status | `APPROVED` |", production_text)

    # --- Test 43: QA cannot approve content ---
    def test_content_item_status_never_touched(self):
        build_passing_item(self.root)
        content_item_before = (self.root / "CONTENT_ITEM.md").read_text(encoding="utf-8")
        run_production_qa(self.root, apply=True)
        content_item_after = (self.root / "CONTENT_ITEM.md").read_text(encoding="utf-8")
        self.assertEqual(content_item_before, content_item_after)
        self.assertIn("Current status: `APPROVED`", content_item_after)

    def test_dry_run_makes_no_mutation(self):
        build_passing_item(self.root)
        before = {p: p.read_text(encoding="utf-8") for p in self.root.rglob("*.md")}
        result = run_production_qa(self.root, apply=False)
        after = {p: p.read_text(encoding="utf-8") for p in self.root.rglob("*.md")}
        self.assertEqual(before, after)
        self.assertFalse(result.produced)
        self.assertFalse((self.root / "qa").exists())


if __name__ == "__main__":
    unittest.main()
