"""Renders a VoiceResult as a fresh VOICE.md file matching
templates/VOICE.md. Only ever called when no voice/voice-<n>.md already
exists for this content item — see pipeline.py's staleness handling /
CONTRACT.md's "Re-running" section.
"""
from __future__ import annotations

from datetime import date, datetime, timezone

from .models import VoiceResult


def render_voice_markdown(result: VoiceResult, today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()
    qa_notes = "; ".join(result.qa_reasons) if result.qa_reasons else "no issues found"
    placeholder_banner = (
        "\n**TEST / PLACEHOLDER AUDIO — not real speech, not "
        "production-quality.** See `agents/voice/README.md`.\n"
        if result.is_placeholder
        else ""
    )

    return f"""# Voice: {result.content_id}

Generated by `agents/voice` (Phase 7C-1 MVP) per
`agents/voice/CONTRACT.md`.
{placeholder_banner}
| Field | Value |
|---|---|
| Voice ID | `{result.voice_id}` |
| Content ID | `{result.content_id}` |
| Provider | `{result.provider_label}` |
| Voice configuration | {result.voice_configuration} |
| Script content hash | `{result.script_content_hash}` |

## Narration source

{result.source_narration}

Provider-ready narration (deterministic quote/whitespace normalization
only, never a content change — see CONTRACT.md's "Narration integrity"):
{result.provider_ready_narration}

## Generated audio

| Field | Value |
|---|---|
| Reference | `{result.audio_reference}` |
| Duration | `{result.duration_seconds}s` |

## Generation status

`{result.generation_status}`

## QA status

`{result.qa_status}`

{qa_notes}

Generated on {today.isoformat()}.
"""
