"""Renders a fresh PRODUCTION.md from a Producer run's scenes, matching
templates/PRODUCTION.md. Only ever called when no PRODUCTION.md already
exists for this content item — see pipeline.py's staleness handling /
CONTRACT.md's "Re-running" section.
"""
from __future__ import annotations

from datetime import date, datetime, timezone

from .models import SceneDraft


def render_production_markdown(
    content_id: str,
    production_id: str,
    script_content_hash: str,
    scenes: list[SceneDraft],
    today: date | None = None,
) -> str:
    today = today or datetime.now(timezone.utc).date()
    total_duration = sum(s.duration_seconds for s in scenes)
    scene_files = ", ".join(f"`{s.filename}`" for s in scenes)
    scene_rows = "\n".join(
        f"| `scene-{s.order:02d}` | `{s.duration_seconds}s` | `NOT_YET_PLANNED` | "
        f"{', '.join(f'`{c}`' for c in s.claim_ids) if s.claim_ids else 'N/A'} | `NOT_STARTED` |"
        for s in scenes
    )

    return f"""# Production: {content_id}

Generated by `agents/producer` (Phase 7B MVP) per
`agents/producer/CONTRACT.md`. Structural output only — narration
decomposed into scenes and claim references carried forward; no visual,
voice, or asset work has happened yet.

## Identity

| Field | Value |
|---|---|
| Content ID | `{content_id}` |
| Production ID | `{production_id}` |
| Script version | `SCRIPT.md` |
| Script content hash | `{script_content_hash}` |
| Production status | `PRODUCTION_PLANNING` |
| Total target duration | `{total_duration}s` |

## Production status

Current: `PRODUCTION_PLANNING`. Set by `agents/producer` on
{today.isoformat()} — this is the Producer's own terminal output state; it
does not advance `VOICE`/`VISUAL_PLANNING` itself (see
`agents/voice/CONTRACT.md` / `agents/visual_planner/CONTRACT.md`).

## Separation from content lifecycle

`CONTENT_ITEM.md`'s `status` is unaffected by this file —
`agents/producer` never writes to `CONTENT_ITEM.md` at all. See
`templates/PRODUCTION.md`'s "Separation from content lifecycle".

## Linked records

- Script: `SCRIPT.md`
- Scenes: {scene_files}
- Assets: none yet — see `agents/visual_planner/`
- Voiceover: none yet — see `agents/voice/`
- Final QA/publication gate: `templates/VIDEO_QA.md` (not started — no
  production work has happened)

## Scene list

| Scene ID | Duration | Visual type | Claims referenced | Status |
|---|---|---|---|---|
{scene_rows}

## Voiceover information

| Field | Value |
|---|---|
| Voice record | not yet created — see `agents/voice/` |
| Narration source | `SCRIPT.md` Hook + Narrative beats |
| Generation status | `NOT_STARTED` |

## Visual requirements (rollup)

Not yet planned — see `agents/visual_planner/`, which populates this
section once real visual planning has happened. Nothing to roll up yet.

## Captions

| Field | Value |
|---|---|
| Source | Derived from each scene's Narration text |
| Status | `NOT_STARTED` |

## Music / audio

Not yet planned — see individual `scenes/scene-<n>.md` files.

## Transitions

Cut between all scenes (Producer default) — see individual
`scenes/scene-<n>.md` files for per-scene In/Out values.

## Asset references (rollup)

Not yet planned — see `agents/visual_planner/`, which populates this
section once real asset requirements exist. Nothing to roll up yet.

## Assembly / Output

| Field | Value |
|---|---|
| Timeline reference | not yet produced |
| Video output reference | not yet produced |
| Assembly status | `NOT_STARTED` |

## Thumbnail

| Field | Value |
|---|---|
| Asset reference | not yet produced |
| Status | `NOT_STARTED` |

## Title / description

| Field | Value |
|---|---|
| Working title | Not yet drafted — see `CONTENT_ITEM.md` |
| Description | Not yet drafted. |

## Production QA state

| Field | Value |
|---|---|
| State | `NOT_STARTED` |
| Notes | No production work has happened yet. |

## Human review state

| Field | Value |
|---|---|
| State | `NOT_STARTED` |
| Reviewer | N/A |
| Notes | N/A |

## Notes / history log

- {today.isoformat()} — Created by `agents/producer` (Production ID
  `{production_id}`) from `SCRIPT.md` (content hash `{script_content_hash}`),
  {len(scenes)} scene(s). See `agents/producer/CONTRACT.md`.
"""
