"""Renders a SceneDraft as a SCENE.md file matching templates/SCENE.md.
Visual/asset/music fields are deliberately generic placeholders — the
Producer never assigns a final visual (CONTRACT.md's Forbidden actions);
agents/visual_planner/ finalizes them.
"""
from __future__ import annotations

from .models import SceneDraft


def render_scene_markdown(scene: SceneDraft, content_id: str, total_scenes: int) -> str:
    claim_refs = ", ".join(f"`{c}`" for c in scene.claim_ids) if scene.claim_ids else "N/A"
    classifications = (
        ", ".join(scene.classifications_present)
        if scene.classifications_present
        else "N/A — no claims referenced"
    )
    in_transition = "N/A (opening scene)" if scene.order == 1 else "cut"
    out_transition = "N/A (final scene)" if scene.order == total_scenes else "cut"

    return f"""# Scene {scene.order:02d}

Generated by `agents/producer` (Phase 7B MVP) per
`agents/producer/CONTRACT.md`. Visual/asset/music fields below are
first-pass placeholders only, not a final plan — see
`agents/visual_planner/`.

| Field | Value |
|---|---|
| Scene ID | `{scene.scene_id}` |
| Content ID | `{content_id}` |
| Order | {scene.order} |
| Duration | `{scene.duration_seconds}s` |

## Narration

| Field | Value |
|---|---|
| Script reference | {scene.script_reference} |
| Narration text | {scene.narration_text} |

## Visual

| Field | Value |
|---|---|
| Visual type | `NOT_YET_PLANNED` |
| Visual description | Not yet planned — see `agents/visual_planner/`. |
| Asset requirement | N/A — not yet planned |

## Caption text

{scene.narration_text}

## Music / audio requirement

`NOT_YET_PLANNED`

## Transition

| Field | Value |
|---|---|
| In | {in_transition} |
| Out | {out_transition} |

## Source / claim references

{claim_refs}

Classifications present (read-only, from `claims/*.md`): {classifications}

## Generation/retrieval status

`NOT_STARTED`

## QA status

`NOT_STARTED`
"""
