"""Renders a SafetyReviewResult as a REVIEW.md file matching
templates/REVIEW.md's structure, role SAFETY_REVIEWER.
"""
from __future__ import annotations

from datetime import date, datetime, timezone

from .models import SafetyReviewResult

REVIEWER_LABEL = "AI-assisted: safety-reviewer-agent-mvp (pending human confirmation)"
ROLE = "SAFETY_REVIEWER"


def render_review_markdown(result: SafetyReviewResult, attempt: int, today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()
    reasons = "\n".join(f"{i}. {r}" for i, r in enumerate(result.reasons, 1)) or "(none)"
    required = (
        "\n".join(f"- {c}" for c in result.required_changes)
        if result.required_changes
        else "(none — verdict is PASS)"
    )
    signal_lines = "\n".join(
        f"- {e.signal.value}: {e.risk_level.value} — {e.reason}"
        for e in result.signal_evaluations
    )
    notes = "\n".join(f"- {n}" for n in result.notes) or "(none)"

    return f"""# Review: {ROLE} attempt {attempt} — {result.content_id}

Generated by `agents/safety` (Phase 6 MVP) per `agents/safety/CONTRACT.md`.
Not a substitute for human sign-off — see `CONSTITUTION.md` rule 1.
Pattern/structural detection only — see `agents/safety/README.md` "Known
limitations" before treating a `LOW_RISK` signal as a safety guarantee.

| Field | Value |
|---|---|
| Content ID | `{result.content_id}` |
| Reviewer role | `{ROLE}` |
| Reviewer | {REVIEWER_LABEL} |
| Review date | {today.isoformat()} |
| Verdict | `{result.verdict.value}` |
| Reviewed content hash | `{result.content_hash}` |

## Reasons

{reasons}

## Required changes (if REVISION_REQUIRED)

{required}

## Notes

Signal evaluations:

{signal_lines}

{notes}
"""
