"""Tests 26, 27, 28: QA catches a missing/invalid strategy value, an
invalid authenticity value, and missing provenance (an unprovenanced
HUMAN_PROVIDED asset that isn't flagged REVIEW_REQUIRED). Direct unit
tests of the pure evaluate_asset_qa function — structural checks only,
never a visual-quality judgment.
"""
import unittest
from pathlib import Path

from ..src.models import AssetPlan, AssetStrategy, HistoricalAuthenticity, SceneVisualRecord
from ..src.qa import evaluate_asset_qa


def _make_scene(claim_ids=None) -> SceneVisualRecord:
    return SceneVisualRecord(
        path=Path("scenes/scene-02.md"), filename="scene-02.md", scene_id="test-item-scene-02",
        content_id="test-item", order=2, narration_text="Some narration.",
        visual_type="ARCHIVAL_IMAGE", visual_description="A period photo.",
        claim_ids=claim_ids or ["c1"],
    )


def _valid_plan(**overrides) -> AssetPlan:
    base = dict(
        scene=_make_scene(), asset_id="test-item-asset-02", filename="asset-02.md",
        asset_type="IMAGE", strategy=AssetStrategy.GENERATED,
        authenticity=HistoricalAuthenticity.GENERATED_RECONSTRUCTION,
        basis="basis text", source="generated by local-test-generated-asset-provider",
        source_url="N/A", generation_prompt="A period photo.", generation_status="GENERATED",
        verification_status="NOT_STARTED", verification_notes="not yet verified",
        content_hash="abc123", artifact_filename="asset-02.generated.txt",
    )
    base.update(overrides)
    return AssetPlan(**base)


class AssetQATests(unittest.TestCase):
    def test_all_valid_inputs_pass(self):
        passed, reasons = evaluate_asset_qa(_valid_plan(), known_claim_ids={"c1"})
        self.assertTrue(passed)
        self.assertEqual(reasons, [])

    # --- Test 26: missing/invalid strategy fails safely ---
    def test_catches_invalid_strategy(self):
        plan = _valid_plan(strategy="NOT_A_REAL_STRATEGY")
        passed, reasons = evaluate_asset_qa(plan, known_claim_ids={"c1"})
        self.assertFalse(passed)
        self.assertTrue(any("strategy" in r for r in reasons))

    # --- Test 27: invalid authenticity value ---
    def test_catches_invalid_authenticity_value(self):
        plan = _valid_plan(authenticity="NOT_A_REAL_VALUE")
        passed, reasons = evaluate_asset_qa(plan, known_claim_ids={"c1"})
        self.assertFalse(passed)
        self.assertTrue(any("authenticity" in r for r in reasons))

    # --- Test 28: missing provenance (unprovenanced HUMAN_PROVIDED) ---
    def test_catches_missing_provenance_on_human_provided_asset(self):
        plan = _valid_plan(
            strategy=AssetStrategy.HUMAN_PROVIDED,
            source="unknown",
            generation_status="HUMAN_PROVIDED",
            verification_status="NOT_STARTED",  # should have been REVIEW_REQUIRED
        )
        passed, reasons = evaluate_asset_qa(plan, known_claim_ids={"c1"})
        self.assertFalse(passed)
        self.assertTrue(any("REVIEW_REQUIRED" in r for r in reasons))

    def test_catches_unresolved_claim_reference(self):
        plan = _valid_plan(scene=_make_scene(claim_ids=["c99"]))
        passed, reasons = evaluate_asset_qa(plan, known_claim_ids={"c1"})
        self.assertFalse(passed)
        self.assertTrue(any("claim references" in r for r in reasons))

    def test_catches_generated_asset_with_no_artifact(self):
        plan = _valid_plan(artifact_filename="")
        passed, reasons = evaluate_asset_qa(plan, known_claim_ids={"c1"})
        self.assertFalse(passed)
        self.assertTrue(any("no artifact reference" in r for r in reasons))

    def test_catches_retrieved_asset_falsely_claiming_retrieval(self):
        plan = _valid_plan(
            strategy=AssetStrategy.RETRIEVED,
            authenticity=HistoricalAuthenticity.AUTHENTIC_HISTORICAL_MEDIA,
            source="not yet sourced", generation_status="RETRIEVED", artifact_filename="",
        )
        passed, reasons = evaluate_asset_qa(plan, known_claim_ids={"c1"})
        self.assertFalse(passed)
        self.assertTrue(any("RETRIEVED" in r for r in reasons))

    def test_catches_retrieved_asset_with_fabricated_url(self):
        plan = _valid_plan(
            strategy=AssetStrategy.RETRIEVED,
            authenticity=HistoricalAuthenticity.AUTHENTIC_HISTORICAL_MEDIA,
            source="https://example.com/fake-archive", generation_status="NOT_STARTED",
            artifact_filename="",
        )
        passed, reasons = evaluate_asset_qa(plan, known_claim_ids={"c1"})
        self.assertFalse(passed)
        self.assertTrue(any("no real retrieval" in r for r in reasons))


if __name__ == "__main__":
    unittest.main()
