"""Renders an AssetPlan as a full templates/ASSET.md file. Always a
complete rewrite — see CONTRACT.md's "Relationship to
agents/visual_planner/" for why completing a Visual-Planner-created
skeleton this way is not "overwriting history": nothing but a
classification decision existed there yet, and once this agent's own
`Scene/visual content hash` is written, normal hash-based staleness rules
(pipeline.py) take over and this function is never called again for that
asset unless the underlying scene actually changed.
"""
from __future__ import annotations

from datetime import date, datetime, timezone

from .models import AssetPlan


def render_asset_markdown(plan: AssetPlan, content_id: str, today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()
    generation_prompt = plan.generation_prompt or "N/A"
    placeholder_banner = (
        "\n**TEST / PLACEHOLDER GENERATED ASSET — not a real image, "
        "video, or audio file.**\n"
        if plan.strategy.value == "GENERATED"
        else ""
    )
    file_reference = f"`assets/{plan.artifact_filename}`" if plan.artifact_filename else "not yet produced"

    return f"""# Asset: {plan.scene.filename} visual requirement

Generated by `agents/assets` (Phase 7C-2 MVP) per
`agents/assets/CONTRACT.md`.
{placeholder_banner}
| Field | Value |
|---|---|
| Asset ID | `{plan.asset_id}` |
| Content ID | `{content_id}` |
| Asset type | `{plan.asset_type}` |
| Intended scene | `scenes/{plan.scene.filename}` |
| Scene/visual content hash | `{plan.content_hash}` |

## Provenance

| Field | Value |
|---|---|
| Generated vs. retrieved | `{plan.strategy.value}` |
| Source | {plan.source} |
| Source URL / reference | {plan.source_url} |
| Generation prompt/reference | {generation_prompt} |

## Historical authenticity classification

| Field | Value |
|---|---|
| Classification | `{plan.authenticity.value}` |
| Basis for classification | {plan.basis} |

## Licensing / copyright

| Field | Value |
|---|---|
| Licensing/provenance status | `UNVERIFIED` |
| Copyright/provenance notes | not yet checked — see Verification status below |

## Technical

| Field | Value |
|---|---|
| Dimensions / aspect ratio | TBD |
| File reference | {file_reference} |

## Generation/retrieval status

`{plan.generation_status}`

## Verification status

`{plan.verification_status}`

{plan.verification_notes}

Generated on {today.isoformat()}.
"""
