"""The Visual Safety Rule, reimplemented here (not imported from
agents/visual_planner/src/classification.py) per this repo's established
sibling-agent boundary — see CONTRACT.md's "Authenticity classification"
for why: production agents reuse only generic infrastructure across each
other, never another agent's own domain judgment, so no agent's safety
behavior can be silently altered by changing a different agent's code.

Deterministic, driven only by claim Classification values — no NLP, no
creativity, and (per this phase's explicit rule) never derived from a
filename or an acquisition strategy.
"""
from __future__ import annotations

from ...researcher.src.models import Claim, Classification
from .models import AssetStrategy, HistoricalAuthenticity, SceneVisualRecord

NON_FACT_CLASSIFICATIONS = frozenset(
    {Classification.ASSUMPTION, Classification.INFERENCE, Classification.SPECULATION}
)


def classify_authenticity(
    scene: SceneVisualRecord, claims: dict[str, Claim]
) -> tuple[HistoricalAuthenticity, str]:
    if not scene.claim_ids:
        return (
            HistoricalAuthenticity.NOT_APPLICABLE,
            "No claim references — not a representational depiction (Visual Safety Rule).",
        )

    referenced_classifications = {claims[cid].classification for cid in scene.claim_ids}

    if referenced_classifications & NON_FACT_CLASSIFICATIONS:
        return (
            HistoricalAuthenticity.GENERATED_RECONSTRUCTION,
            "At least one referenced claim is ASSUMPTION/INFERENCE/SPECULATION — this "
            "scene depicts something that did not (or may not have) actually happened "
            "as stated, so it must never be classified AUTHENTIC_HISTORICAL_MEDIA "
            "(Visual Safety Rule).",
        )

    return (
        HistoricalAuthenticity.AUTHENTIC_HISTORICAL_MEDIA,
        "All referenced claims are FACT. This classification states sourcing intent "
        "only — Verification status stays NOT_STARTED until a specific, provenanced "
        "item is actually confirmed; if no genuinely authentic item can be sourced, "
        "this classification must be revisited, never left as an unverified claim.",
    )


def default_strategy_for(authenticity: HistoricalAuthenticity) -> AssetStrategy:
    """A real historical item must be sourced, never generated; anything
    else (a reconstruction, or a non-representational graphic) is
    generated by default. HUMAN_PROVIDED is never a default — a caller
    must explicitly opt a scene into it (CONTRACT.md's Asset strategies).
    """
    if authenticity is HistoricalAuthenticity.AUTHENTIC_HISTORICAL_MEDIA:
        return AssetStrategy.RETRIEVED
    return AssetStrategy.GENERATED
