"""Renders a CaptionsResult as a full templates/CAPTIONS.md file."""
from __future__ import annotations

from datetime import date, datetime, timezone

from .models import CaptionsResult


def render_captions_markdown(result: CaptionsResult, content_id: str, today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()

    scene_sections = []
    for scene in result.scenes:
        rows = "\n".join(
            f"| {c.index} | `{c.start}s` | `{c.end}s` | {c.text} |" for c in scene.chunks
        )
        if not rows:
            rows = "| — | — | — | (no narration to caption) |"
        scene_sections.append(
            f"### Scene `{scene.scene_id}`\n\n"
            f"| Caption # | Start | End | Text |\n"
            f"|---|---|---|---|\n"
            f"{rows}"
        )
    scenes_text = "\n\n".join(scene_sections)

    return f"""# Captions: {content_id}

Generated by `agents/captions` (Phase 7D MVP) per
`agents/captions/CONTRACT.md`. Every caption's text is a verbatim
substring of its source scene's Narration text — no paraphrasing, no
qualifiers removed.

| Field | Value |
|---|---|
| Captions ID | `{result.captions_id}` |
| Content ID | `{content_id}` |
| Production ID | `{result.production_id}` |
| Captions content hash | `{result.captions_content_hash}` |
| Max characters per line | `{result.max_characters_per_line}` |
| Max lines per caption | `{result.max_lines_per_caption}` |

## Scene captions

{scenes_text}

## Generation status

`{result.generation_status}`

Generated on {today.isoformat()}.
"""
