"""Renders one Bounded Research Mode EvaluatedSource (research.py) as a
templates/RESEARCH.md-formatted file. Kept separate from research.py's
evaluation logic the same way review_writer.py/revision_writer.py are kept
separate from factcheck.py/revision.py — one module per concern.

Written for every evaluated source, accepted or rejected alike (Phase 7G:
"full auditability" — see agents/researcher/CONTRACT.md's "Bounded Research
Mode" -> "Structured research record"). Never invents a field research.py
didn't already determine; a value this module can't derive is rendered as
"N/A" or "unknown", never guessed.
"""
from __future__ import annotations

from .models import Claim

RESEARCHER_NOTE_PREFIX = (
    "AI-assisted: researcher-agent Bounded Research Mode "
    "(agents/researcher/src/research.py) — pending human review"
)


def _retrieved_date(retrieved_at: str) -> str:
    return retrieved_at.split("T", 1)[0] if retrieved_at else "unknown"


def render_research_entry_markdown(claim: Claim, evaluated) -> str:
    """`evaluated` is a research.EvaluatedSource. Typed loosely (not
    imported) to avoid a circular import between research.py and this
    module — research.py imports render_research_entry_markdown, so this
    module must not import back from research.py.
    """
    result = evaluated.provider_result
    retrieval_verified = "YES" if result.retrieval_verified else "NO"
    conflicting_evidence = (
        "none found" if evaluated.discovery_status.value == "ACCEPTED" else "N/A"
    )

    return f"""# Research Entry — {result.source_title or "(untitled source)"}

Generated by `agents/researcher/src/research.py`'s Bounded Research Mode,
per `agents/researcher/CONTRACT.md`'s "Bounded Research Mode". This record
never grants approval and never asserts the underlying claim is correct on
its own — see `templates/RESEARCH.md`.

| Field | Value |
|---|---|
| Content ID | `{claim.content_id}` |
| Source | {result.source_title or "N/A"} |
| Source type | `OTHER` (not determinable from provider output alone) |
| Source URL / reference | `{result.source_url or "N/A"}` |
| Publication date | `{result.publication_date or "unknown"}` |
| Retrieved date | `{_retrieved_date(result.retrieved_at)}` |
| Source reliability | `{evaluated.reliability.value}` |
| Discovery status | `{evaluated.discovery_status.value}` |
| Provider result ID | `{result.provider_result_id or "N/A"}` |
| Retrieval verified | `{retrieval_verified}` |

## Relevant evidence

{result.evidence_excerpt or "N/A"}

## Related claims

`{claim.short_id}`

## Claim support relationship

`{evaluated.claim_support.value}`

## Conflicting evidence

{conflicting_evidence}

## Rejection reason

{evaluated.rejection_reason}

## Researcher notes

{RESEARCHER_NOTE_PREFIX}. Reliability assessment: {evaluated.reliability_reason}
"""
