"""Renders a ClaimRevisionOutcome as a templates/REVISION.md file. Kept
separate from revision.py's diagnosis/creation logic the same way
review_writer.py is kept separate from factcheck.py — one module per
concern.
"""
from __future__ import annotations

from datetime import date, datetime, timezone

from .models import ClaimRevisionOutcome, RevisionStatus

REVISION_AUTHOR = "AI-assisted: researcher-agent revision engine (pending human confirmation)"


def render_revision_markdown(
    revision_id: str,
    content_id: str,
    outcome: ClaimRevisionOutcome,
    triggering_attempt: int,
    status: RevisionStatus,
    today: date | None = None,
) -> str:
    today = today or datetime.now(timezone.utc).date()
    successor_cell = f"`claims/{outcome.successor_short_id}.md`" if outcome.successor_short_id else "N/A"
    new_hash_cell = f"`{outcome.new_hash}`" if outcome.new_hash else "N/A"
    verification_cell = outcome.verification_result or "N/A"
    escalation_state = "NOT_REQUIRED" if outcome.successor_short_id else "REQUIRED"
    evidence_cell = ", ".join(f"`{e}`" for e in outcome.evidence_used) or "N/A"
    changes_cell = outcome.changes_made or "(no successor created — see Notes)"

    return f"""# Revision: {revision_id}

Generated by `agents/researcher/src/revision.py`'s Autonomous Revision
Mode, per `agents/researcher/CONTRACT.md`'s "Autonomous Revision Mode".
This record never grants approval — see "What this record does NOT do"
in `templates/REVISION.md`.

| Field | Value |
|---|---|
| Revision ID | `{revision_id}` |
| Original claim ID | `claims/{outcome.original_short_id}.md` |
| Successor claim ID | {successor_cell} |
| Triggering review attempt | `reviews/fact_checker-{triggering_attempt}.md` |
| Reason for revision | {outcome.reason} |
| Original claim hash | `{outcome.original_hash}` |
| New claim hash | {new_hash_cell} |
| Evidence used | {evidence_cell} |
| Changes made | {changes_cell} |
| Revision author | {REVISION_AUTHOR} |
| Revision timestamp | {today.isoformat()} |
| Revision status | `{status.value}` |
| Verification result | {verification_cell} |
| Human escalation state | `{escalation_state}` |

## Changes made

{changes_cell}

## Notes

{outcome.reason}

## What this record does NOT do

This record never grants approval of any kind. A `SUCCESSOR_CREATED`
status means a corrected, evidence-complete claim now exists — it does
**not** mean `CONTENT_ITEM.md` is `APPROVED`, does not advance
`Production status`, and does not itself change `SCRIPT.md`.
"""
