"""Renders a FactCheckResult as a REVIEW.md file matching
templates/REVIEW.md's structure exactly (including the Phase 5
`Reviewed content hash` field).
"""
from __future__ import annotations

from datetime import date, datetime, timezone

from .models import FactCheckResult

REVIEWER_LABEL = "AI-assisted: researcher-agent-mvp (pending human confirmation)"
ROLE = "FACT_CHECKER"


def render_review_markdown(result: FactCheckResult, attempt: int, today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()
    reasons = "\n".join(f"{i}. {r}" for i, r in enumerate(result.reasons, 1)) or "(none)"
    required = (
        "\n".join(f"- {c}" for c in result.required_changes)
        if result.required_changes
        else "(none — verdict is PASS)"
    )
    notes = "\n".join(f"- {n}" for n in result.notes) or "(none)"

    return f"""# Review: {ROLE} attempt {attempt} — {result.content_id}

Generated by `agents/researcher` (Phase 5 MVP) per
`agents/researcher/CONTRACT.md`. Not a substitute for human sign-off —
see `CONSTITUTION.md` rule 1.

| Field | Value |
|---|---|
| Content ID | `{result.content_id}` |
| Reviewer role | `{ROLE}` |
| Reviewer | {REVIEWER_LABEL} |
| Review date | {today.isoformat()} |
| Verdict | `{result.verdict.value}` |
| Reviewed content hash | `{result.content_hash}` |

## Reasons

{reasons}

## Required changes (if REVISION_REQUIRED)

{required}

## Notes

{notes}
"""
