"""Renders an AssemblyResult as a full templates/TIMELINE.md file. Always
a complete rewrite — only ever called when no timeline/timeline-<n>.md
already exists, or when it does and is being freshly (re)computed for
the first time (see pipeline.py's staleness handling).
"""
from __future__ import annotations

from datetime import date, datetime, timezone

from .models import AssemblyResult


def render_timeline_markdown(result: AssemblyResult, content_id: str, today: date | None = None) -> str:
    today = today or datetime.now(timezone.utc).date()
    rows = "\n".join(
        f"| `{s.scene_id}` | `{s.start}s` | `{s.end}s` | `{s.duration_seconds}s` | "
        f"`{s.narration_reference}` | `{s.visual_reference}` | `{s.captions_reference}` | "
        f"{s.transition_in} / {s.transition_out} | "
        f"{', '.join(f'`{c}`' for c in s.claim_ids) if s.claim_ids else 'N/A'} |"
        for s in result.scenes
    )

    return f"""# Timeline: {content_id}

Generated by `agents/assembler` (Phase 7D MVP) per
`agents/assembler/CONTRACT.md`.

| Field | Value |
|---|---|
| Timeline ID | `{result.timeline_id}` |
| Content ID | `{content_id}` |
| Production ID | `{result.production_id}` |
| Assembly content hash | `{result.assembly_content_hash}` |
| Total duration | `{result.total_duration}s` |

## Scene timeline

| Scene ID | Start | End | Duration | Narration/audio reference | Visual asset reference | Captions reference | Transition | Claim references |
|---|---|---|---|---|---|---|---|---|
{rows}

## Output

| Field | Value |
|---|---|
| Renderer | `{result.renderer_label}` |
| Video reference | `{result.output_reference}` |
| Format | `{result.output_format}` |
| Output hash | `{result.output_hash}` |
| Playable | `{result.playable}` |

## Assembly status

`{result.assembly_status}`

Generated on {today.isoformat()}.
"""
